name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Python
        run: python -m compileall .


  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Install Ruff
        run: pip install ruff

      - name: Lint
        run: ruff check .
